EcommerceSistemaVsShopify/Controllers/ExistenciaShopifyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EcommerceSistemaVsShopify.Models;
using Microsoft.AspNetCore.Mvc;
using ShopifySharp;
using ShopifySharp.Filters;

namespace EcommerceSistemaVsShopify.Controllers
{
    public class ExistenciaShopifyController:Controller
    {


        public async Task<IActionResult> GetList([FromQuery]string page_info,int cantidad_items=50)
        {


            int LimiteporPagina= cantidad_items;
            ListFilter<Product> filtropagina;
            if(!string.IsNullOrEmpty(page_info))
            {
                filtropagina = new ListFilter<Product>(page_info,LimiteporPagina);
            }
            else
            {
                filtropagina = new ProductListFilter
                {
                    Limit = LimiteporPagina
                };
            }
            var servicioProducto= new ProductService(CadenaDeConexionManager.UrlTienda,CadenaDeConexionManager.Contrasenia);
            var productos=await servicioProducto.ListAsync(filtropagina);


            return View(productos);
        }

        public IActionResult Index( )
        {
            ViewBag.Msg = "Mensaje Index "+this.GetType().ToString();
            return View();
        }

    }
}

EcommerceSistemaVsShopify/Controllers/ExistenciasBusquedaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EcommerceSistemaVsShopify.Repository;
using System.Text.RegularExpressions;
using EcommerceSistemaVsShopify.Models;
using X.PagedList;

namespace EcommerceSistemaVsShopify.Controllers
{

    public class ExistenciasBusquedaController:Controller
    {
        IExistenciasEcommerce _IExistenciasBusqueda;
        public ExistenciasBusquedaController(IExistenciasEcommerce IExistenciasBusqueda)
        {
            _IExistenciasBusqueda = IExistenciasBusqueda;
        }
        public IActionResult Grilla(string buscar,int ordenarpor,bool isAscendente = true,int? page=1)
        {
            //int? page=1;
            string valorbusqueda= string.Empty;
            if(!string.IsNullOrEmpty(buscar))
            {
                valorbusqueda = Regex.Replace(buscar,@"[^a-zA-Z0-9\s]",String.Empty);
            }
            if(page<0)
            {
                page = 1;
            }
            ExistenciasEcommerceInfoPaginacion infoPaginacion= new ExistenciasEcommerceInfoPaginacion();
            var indicepagina=(page??1)-1;
            var  tamaniopagina=50;
            string columnaorden;
            #region Ordenandocolumna
            switch(ordenarpor)
            {
                case 0:
                    if(isAscendente)
                    {
                        columnaorden = "PLM";
                    }
                    else
                    {
                        columnaorden = "PLM Desc";
                    }
                    break;
                case 1:
                    if(isAscendente)
                    {
                        columnaorden = "CodigoProducto";
                    }
                    else
                    {
                        columnaorden = "CodigoProducto Desc";
                    }
                    break;
                case 2:
                    if(isAscendente)
                    {
                        columnaorden = "NombreProducto";
                    }
                    else
                    {
                        columnaorden = "NombreProducto Desc";
                    }
                    break;
                case 3:
                    if(isAscendente)
                    {
                        columnaorden = "Existencia";
                    }
                    else
                    {
                        columnaorden = "Existencia Desc";
                    }
                    break;
                case 4:
                    if(isAscendente)
                    {
                        columnaorden = "COLECCION";
                    }
                    else
                    {
                        columnaorden = "COLECCION Desc";
                    }
                    break;
                case 5:
                    if(isAscendente)
                    {
                        columnaorden = "Temporada";
                    }
                    else
                    {
                        columnaorden = "Temporada Desc";
                    }
                    break;
                case 6:
                    if(isAscendente)
                    {
                        columnaorden = "UnidadNegocio";
                    }
                    else
                    {
                        columnaorden = "UnidadNegocio Desc";
                    }
                    break;
                case 7:
                    if(isAscendente)
                    {
                        columnaorden = "Precio_Neto";
                    }
                    else
                    {
                        columnaorden = "Precio_Neto Desc";
                    }
                    break;
                default:
                    columnaorden = "NombrePorducto";
                    break;
            }
            #endregion
            int totalLineas= _IExistenciasBusqueda.GetCantidadExistencias(valorbusqueda);
            var Existencias=_IExistenciasBusqueda.ExistenciasEcommercePaginacion(valorbusqueda,columnaorden,page,tamaniopagina).ToList();
            var ExistenciasPaginadas= new StaticPagedList<ExistenciasEcommerceModelo>(Existencias,indicepagina+1,tamaniopagina,totalLineas);

            infoPaginacion.Existencias = ExistenciasPaginadas;
            infoPaginacion.TamanioPagina = tamaniopagina;
            infoPaginacion.Buscar = valorbusqueda;
            infoPaginacion.OrdenarPor = ordenarpor;
            infoPaginacion.isAscendente = isAscendente;
            return View(infoPaginacion);

        }
        public IActionResult Index( )
        {
            ViewBag.Mensaje = "AQUI TOYyyy";
            return View();
        }
    }
}

EcommerceSistemaVsShopify/Views/Shared/_DevExtremeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EcommerceSistemaVsShopify</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.min.js"></script> *@

    @* Uncomment to use the Gantt control *@
    @*<link href="~/css/devextreme/dx-gantt.css" rel="stylesheet" />*@

    @* Uncomment to use the Diagram control *@
    @*<link href="~/css/devextreme/dx-diagram.css" rel="stylesheet" />*@

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />

    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    @* Uncomment to use the Gantt control *@
    @*<script src="~/js/devextreme/dx-gantt.js"></script>*@

    @* Uncomment to use the Diagram control *@
    @*<script src="~/js/devextreme/dx-diagram.js"></script>*@

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    @* Uncomment to use Globalize for localization *@
    @* Docs: https://docs.devexpress.com/AspNetCore/400577#globalize *@
    @*<script src="~/js/devextreme/cldr.js"></script>*@
    @*<script src="~/js/devextreme/cldr/event.js"></script>*@
    @*<script src="~/js/devextreme/cldr/supplemental.js"></script>*@
    @*<script src="~/js/devextreme/cldr/unresolved.js"></script>*@
    @*<script src="~/js/devextreme/globalize.js"></script>*@
    @*<script src="~/js/devextreme/globalize/message.js"></script>*@
    @*<script src="~/js/devextreme/globalize/number.js"></script>*@
    @*<script src="~/js/devextreme/globalize/currency.js"></script>*@
    @*<script src="~/js/devextreme/globalize/date.js"></script>*@

    @* Uncomment to enable client-side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>

    @* Uncomment to provide geo-data for the VectorMap control *@
    @* Docs: https://js.devexpress.com/DevExtreme/Guide/Widgets/VectorMap/Providing_Data/#Data_for_Areas *@
    @*<script src="~/js/devextreme/vectormap-data/world.js"></script>*@

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
</head>

<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="/">EcommerceSistemaVsShopify</a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="active nav-item"> 
                    <a class="nav-link text-dark" asp-area="" asp-controller="ExistenciasEcommerce" asp-action="Index">Existencias BC</a>
                </li>
</ul>
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>
</body>

</html>

EcommerceSistemaVsShopify/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcommerceSistemaVsShopify</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="ExistenciasBusqueda" asp-action="Grilla">Ecommerce Sistema Vs Shopify</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExistenciasBusqueda" asp-action="Grilla">Existencias BC</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExistenciaShopify" asp-action="GetList">Existenciass Shopifyyy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExistenciaShopify" asp-action="Index">Comparativo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EcommerceSistemaVsShopify - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>